CREATE SCHEMA IF NOT EXISTS `astro-template` DEFAULT CHARACTER SET UTF8;

CREATE TABLE IF NOT EXISTS USER (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    OPTED_IN TINYINT(1) NOT NULL DEFAULT 0,
    CONSTRAINT EMAIL UNIQUE (EMAIL),
    CONSTRAINT USERNAME UNIQUE (USERNAME)
);
